---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/cp353596/public_html/
      - /bin/cp index.php $DEPLOYPATH
      - /bin/cp community-manager.html $DEPLOYPATH
      - /bin/cp developpement-web.html $DEPLOYPATH
      - /bin/cp creation-graphique.html $DEPLOYPATH
      - /bin/cp contact.html $DEPLOYPATH
      - /bin/cp index.css $DEPLOYPATH
      - /bin/cp app.js $DEPLOYPATH
      - /bin/cp -R Assets $DEPLOYPATH
      - /bin/cp -R IMG $DEPLOYPATH
      - /bin/cp -R PHPMailer $DEPLOYPATH
